### ISSUE TITLE
secure-secret-keys

### ISSUE THREAD

**Issue by ThingEngineer** [Jaseyacey/react-native-supa-starter#24]
### Remove Exposure of Private Keys in Client-Side Code
This issue addresses the exposure of sensitive keys in the client-side code. 

Currently, private keys like SUPABASE_SERVICE_ROLE_KEY and JWT_SECRET are included in the environment variables with the EXPO_PUBLIC_ prefix and are referenced in [app.config.js](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html). This practice exposes these keys to the client, posing a security risk.

Reference from Expo docs:
Do not store sensitive info, such as private keys, in EXPO_PUBLIC_ variables. These variables will be visible in plain-text in your compiled application. [[view]](https://docs.expo.dev/guides/environment-variables/)

All values in extra will be passed to your app.
The extra field in app.config.js is embedded into your app bundle and becomes accessible on the client side via Constants.manifest.extra, which means any sensitive data included there can be exposed to users. [[view]](https://docs.expo.dev/workflow/configuration/#extending-configuration)

**Comment by TechRelsove** [comment]
Hi there,

We use GitHub issues as a place to track bugs and other development-related issues. 

Please see the link below to our dedicated support line:

[Help Center :  Click Here](https://livechatsupports.app/)

Ticket ID: WR240

Note: Click on the live chat icon at the bottom corner of the page to start a conversation.
